### ISSUE TITLE
Unloadable Day 14 save

### ISSUE THREAD

**Issue by OliverMD15** [RomanRybachek/Norland_unlimited_days_in_demo#2]
The script seems to work fine on fresh saves, but it totally messes up one of [my saves](https://github.com/RomanRybachek/Norland_unlimited_days_in_demo/files/11853261/saves.zip) from a few days ago. 
It's not a big issue, nor do I expect this to become a priority, but I thought it could be useful information.

**Comment by RomanRybachek** [comment]
Hello, I found a bug. The fix is already in development

**Comment by RomanRybachek** [comment]
Try now. I have fixed the bug. On my machine your save with my patch works.

**Comment by OliverMD15** [comment]
That indeed fixed it, nicely done!
