### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by DaytonFox** [RomanRybachek/Norland_unlimited_days_in_demo#4]
Just didnt see, where i can write comments.

Can i change my game's language back to rus after using the script?
Do you know, can i turn off autosaves?

**Comment by RomanRybachek** [comment]
Yes, you can. The script can already work with saves made in the Russian language version of the game. Thanks to @alexander-trifonov

**Comment by RomanRybachek** [comment]
It was about Russian language. I don't know how to turn off autosaves.

**Comment by alexander-trifonov** [comment]
Probably you can't, because previous version of fix had wrong encoding, so all russian city names and other stuff may corrupt. It's better to make new unlimited_days.save from untouched save

**Comment by RomanRybachek** [comment]
> Probably you can't, because previous version of fix had wrong encoding, so all russian city names and other stuff may corrupt. It's better to make new unlimited_days.save from untouched save

The previous version could not even read files with Russian characters. If the previous version of the script changed the save made in the English version I think he can safely change the language. But it's better to make a backup of the save :)

**Comment by slayer3294** [comment]
PS C:\Users\exmp\AppData\Local\Strategy\saves> python unlim_days.py test.nrlds
Traceback (most recent call last):
  File "C:\Users\exmp\AppData\Local\Strategy\saves\unlim_days.py", line 22, in <module>
    file_body = file_fd.read()
                ^^^^^^^^^^^^^^
  File "<frozen codecs>", line 701, in read
  File "<frozen codecs>", line 504, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 1493351: invalid continuation byte


I'I was trying to run the script and this is what I've been getting. (total noob in python) is there any chance I could get some help?
