### ISSUE TITLE
Economic report bug

### ISSUE THREAD

**Issue by DaytonFox** [RomanRybachek/Norland_unlimited_days_in_demo#5]
![image](https://github.com/RomanRybachek/Norland_unlimited_days_in_demo/assets/137567723/9b7cc310-b863-40bd-b939-f194b262eb63)

**Comment by RomanRybachek** [comment]
Please send save file and unlim_day.save. 
Without these files it is difficult to determine what caused the problem.
The problem may not even be related to the script.

**Comment by DaytonFox** [comment]
[saves.zip](https://github.com/RomanRybachek/Norland_unlimited_days_in_demo/files/11853743/saves.zip)
Sry

**Comment by RomanRybachek** [comment]
> [saves.zip](https://github.com/RomanRybachek/Norland_unlimited_days_in_demo/files/11853743/saves.zip) Sry

It looks as if the files are from different saves. Send the original save with no changes and the one that came out after the script worked.

**Comment by DaytonFox** [comment]
Oh, i dont have vanilla save right now. I will send it later

**Comment by DaytonFox** [comment]
Hello, there are files
[saves.zip](https://github.com/RomanRybachek/Norland_unlimited_days_in_demo/files/11860986/saves.zip)

**Comment by RomanRybachek** [comment]
I'm not sure it can be fixed.
