### ISSUE TITLE
Norland 20 day bypass

### ISSUE THREAD

**Issue by reequired** [RomanRybachek/Norland_unlimited_days_in_demo#7]
do you have anything for the current version of Norland demo? And also could you drop a simplified tutorial on how to execute the script for idiots like me that are very new to this.

Thanks

**Comment by RomanRybachek** [comment]
Hello. Now the script [does not work](https://github.com/RomanRybachek/Norland_unlimited_days_in_demo/issues/6#issuecomment-1627807431) because the script used a bug that's already been fixed. The only way to bypass the restriction is to patch the game, I don't plan to do that.
